AUTOGRAD 자동미분

In [1]:
import torch

requires_grad = True 를 설정하여 연산을 기록

In [14]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [15]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [16]:
z = y*y*3
out = z.mean()

print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


.requires.grad_() 은 기존 tensor의 requires.grad 값을 바꿔치기 하여 변경

In [10]:
x = torch.randn(2,2)
x = (x*3)/(x-1)
print(x.requires_grad)
x.requires_grad_(True)
print(x.requires_grad)
y = (x*x).sum()
print(y.grad_fn)

False
True


Gradient : 변화도

In [17]:
out.backward()

In [21]:
print(x)3
print(x.grad_fn)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


torch.autograd 는 벡터-야코비안 곱을 계산하는 엔진

In [22]:
x = torch.randn(3, requires_grad=True)

y = x*2
while y.data.norm() < 1000:
  y = y*2

print(y)

tensor([ 590.9181, -216.6573,  833.0831], grad_fn=<MulBackward0>)


In [23]:
print(x)

v=torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([ 0.5771, -0.2116,  0.8136], requires_grad=True)
tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


with torch.no_grad(): 를 통하여 autograd가 .requires_grad = True 인 Tensor들의 연산 기록을 추적하는 것을 멈출 수 있음.

In [25]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad() : 
  print((x**2).requires_grad)

True
True
False


.detach()를 이용하여 content는 같지만 requires_grad가 다른 새로운 tensor를 가져올 수 있음

In [28]:
print(x.requires_grad)
y=x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


In [29]:
x = torch.randn(2,2)
print(x.requires_grad)
y=x.detach()
print(y.requires_grad)
print(x.eq(y).all())

False
False
tensor(True)


In [31]:
x = torch.ones(2,2)
y = torch.ones(2,2)
print(x.eq(y).all())

tensor(True)
