In [1]:
from __future__ import print_function
import torch

초기화 되지 않은 5x3 행렬 생성

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[1.2774e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.1657e-44],
        [4.4721e+21, 1.5956e+25, 4.7399e+16],
        [3.7293e-08, 1.4838e-41, 5.7453e-44],
        [1.0689e-38, 0.0000e+00, 0.0000e+00]])


무작위로 초기화된 5x3 행렬 생성

In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.4553, 0.9959, 0.6633],
        [0.4890, 0.7868, 0.5694],
        [0.3568, 0.6964, 0.2960],
        [0.2790, 0.2135, 0.7349],
        [0.3191, 0.5257, 0.2781]])


dtype이 long이고 0으로 채워진 5x3 행렬 생성

In [6]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


직접 tensor 생성

In [7]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


행렬 크기 구하기

In [8]:
print(x.size())

torch.Size([2])


연산

In [9]:
x = torch.rand(5,3)
print(x)
y = torch.rand(5,3)
print(y)

print(x+y)

tensor([[0.1712, 0.9883, 0.1969],
        [0.1863, 0.3576, 0.0983],
        [0.4341, 0.0643, 0.5194],
        [0.3168, 0.9549, 0.1363],
        [0.8964, 0.3753, 0.5922]])
tensor([[0.3641, 0.3638, 0.2071],
        [0.3692, 0.8078, 0.9256],
        [0.5319, 0.6382, 0.2718],
        [0.2482, 0.4478, 0.4588],
        [0.4460, 0.4477, 0.9746]])
tensor([[0.5353, 1.3521, 0.4040],
        [0.5554, 1.1654, 1.0239],
        [0.9660, 0.7025, 0.7912],
        [0.5651, 1.4027, 0.5951],
        [1.3423, 0.8230, 1.5668]])


In [10]:
print(torch.add(x,y))

tensor([[0.5353, 1.3521, 0.4040],
        [0.5554, 1.1654, 1.0239],
        [0.9660, 0.7025, 0.7912],
        [0.5651, 1.4027, 0.5951],
        [1.3423, 0.8230, 1.5668]])


In [13]:
result = torch.rand(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[0.5353, 1.3521, 0.4040],
        [0.5554, 1.1654, 1.0239],
        [0.9660, 0.7025, 0.7912],
        [0.5651, 1.4027, 0.5951],
        [1.3423, 0.8230, 1.5668]])


바꿔치기(in-place) : in-place 방식으로 tensor의 값을 변경하는 연산 뒤에는 _ 가 붙는다.

In [14]:
y.add_(x)
print(y)

tensor([[0.5353, 1.3521, 0.4040],
        [0.5554, 1.1654, 1.0239],
        [0.9660, 0.7025, 0.7912],
        [0.5651, 1.4027, 0.5951],
        [1.3423, 0.8230, 1.5668]])


크기 변경 : tensor의 크기(size)나 모양(shape)을 변경할 때 torch.view를 사용

In [18]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


tensor가 하나의 값을 가지면 .item()을 이용하여 숫자 값을 가지고 옴

In [19]:
x = torch.randn(1)
print(x)
print(x.item())  

tensor([0.8628])
0.8628301024436951


Torch tensor를 Numpy로 변환

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Numpy를 Torch tensor로 변환

In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


numpy -> torch tensor와 그 반대 방향도 가능하다. 두 경우 모두 메모리 공간을 공유하므로 한쪽이 바뀌면 같이 바뀐다.